# https://online-judge-tools.github.io/verification-helper/document.ja.html
#
# - `{basedir}`
#   Expands to the root directroy.
#
# - '{path}'
#   Expands to the source file path relative to the root directroy, like `graph/shortest_paths.hs`.

[languages.haskell]
# call from a problem directroy
compile = "./compile {path}"
execute = "./execute {path}"

verification_file_suffix = ".hs"

# Install `online-judge-verify-helper` with `venv. This works on NixOS, too!:
# $ python -m venv .venv
# (.venv) $ source .venv/bin/activate.fish # activate
# (.venv) $ pip3 install online-judge-verify-helper
# (.venv) $ deactivate

